on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tntaksreg.azurecr.io
        username: ${{ secrets.acr_tntaksreg_username }}
        password: ${{ secrets.acr_tntaksreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t tntaksreg.azurecr.io/atostraplacluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push tntaksreg.azurecr.io/atostraplacluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_atostraplacluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dev | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dev`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dev
        container-registry-url: tntaksreg.azurecr.io
        container-registry-username: ${{ secrets.acr_tntaksreg_username }}
        container-registry-password: ${{ secrets.acr_tntaksreg_password }}
        secret-name: atostraplacldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dev
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          tntaksreg.azurecr.io/atostraplacluster:${{ github.sha }}
        imagepullsecrets: |
          atostraplacldockerauth
